# ==============================================================
# SERVER CONFIGURATION
# ==============================================================
# Ampiasao ny 8081 satria io no efa hitantsika fa misokatra
server.port=8081

# ==============================================================
# DATABASE CONFIGURATION (PostgreSQL)
# ==============================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/mvola
spring.datasource.username=postgres
spring.datasource.password=elyse2004
spring.datasource.driver-class-name=org.postgresql.Driver


spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ==============================================================
# VIEW ENGINE CONFIGURATION (JSP)
# ==============================================================
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# ==============================================================
# MAIL SERVICE CONFIGURATION (Gmail SMTP)
# ==============================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=elhadari04@gmail.com
spring.mail.password=dshlkqcujospzndi

# STARTTLS Configuration (Ilaina amin'ny Gmail)
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.enable=false

# Timeouts
spring.mail.properties.mail.smtp.connectiontimeout=30000
spring.mail.properties.mail.smtp.timeout=30000
spring.mail.properties.mail.smtp.writetimeout=30000